<?xml version="1.0"?>
<package format="3">
  <name>neuroracer_gym</name>
  <version>0.0.0</version>
  <description>neuroracer_gym package</description>

  <maintainer email="aray@todo.todo">aray</maintainer>

  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>neuroracer_sim</exec_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>ros_gz_interfaces</exec_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
